### ISSUE TITLE
Damaged projects in project list

### ISSUE THREAD

**Issue by peendebak** [QuTech-Delft/quantuminspire#101]
# Bug report

## What did you try to do?

Executed algorithms via the SDK. 

## What did you expect to happen?

Normal execution of the algorithms.

## What actually happened?

In the project view I see

![image](https://user-images.githubusercontent.com/17724047/120037236-93141800-c001-11eb-9a80-13687e5938a9.png)

## Environment

Please specify:
* operating system, version and distribution: Windows 10
* python version (`python --version`) and distribution: 3.8

**Comment by QFer** [comment]
@peendebak This happens when a project is created in the Quantum Inspire backend for running your experiment but while preparing the experiment an exception is raised (because an error was detected or the resulting experiment is invalid to run on QI). In some cases the empty project just created is not deleted. When Quantum Inspire is opened these projects are tagged as damaged.

We are working on a solution.

**Comment by QFer** [comment]
Fixed in https://github.com/QuTech-Delft/quantuminspire/pull/102
